import { Agent, Goal, Task, Activity, Company } from "./types";

export const company: Company = {
  name: "Paperclip Co.",
  mission:
    "Build the future of autonomous businesses by orchestrating teams of AI agents that deliver real outcomes with zero human intervention.",
  founded: "2026-03-01",
};

// Fixed timestamps (relative to 2026-07-21T16:00:00Z) to avoid SSR/client hydration mismatch
export const initialAgents: Agent[] = [
  {
    id: "agt-001",
    name: "Zeus",
    role: "CEO",
    status: "working",
    avatar: "⚡",
    budgetMonthly: 500,
    budgetSpent: 187.42,
    lastHeartbeat: "2026-07-21T15:58:00.000Z",
    currentTask: "Reviewing Q3 strategy & allocating resources",
    skills: ["strategy", "delegation", "governance", "vision"],
    model: "claude-opus-4",
  },
  {
    id: "agt-002",
    name: "Athena",
    role: "CTO",
    status: "working",
    avatar: "🛡️",
    budgetMonthly: 400,
    budgetSpent: 312.18,
    lastHeartbeat: "2026-07-21T15:59:15.000Z",
    currentTask: "Architecting multi-agent runtime",
    reportsTo: "agt-001",
    skills: ["architecture", "coding", "devops", "security"],
    model: "claude-sonnet-4",
  },
  {
    id: "agt-003",
    name: "Hermes",
    role: "CMO",
    status: "idle",
    avatar: "📣",
    budgetMonthly: 250,
    budgetSpent: 89.5,
    lastHeartbeat: "2026-07-21T15:48:00.000Z",
    reportsTo: "agt-001",
    skills: ["copywriting", "seo", "social", "brand"],
    model: "gpt-4.1",
  },
  {
    id: "agt-004",
    name: "Apollo",
    role: "Engineer",
    status: "working",
    avatar: "⚙️",
    budgetMonthly: 200,
    budgetSpent: 156.3,
    lastHeartbeat: "2026-07-21T15:59:30.000Z",
    currentTask: "Implementing heartbeat scheduler",
    reportsTo: "agt-002",
    skills: ["typescript", "react", "node", "postgres"],
    model: "claude-sonnet-4",
  },
  {
    id: "agt-005",
    name: "Artemis",
    role: "Designer",
    status: "paused",
    avatar: "🎨",
    budgetMonthly: 150,
    budgetSpent: 42.0,
    lastHeartbeat: "2026-07-21T13:00:00.000Z",
    reportsTo: "agt-002",
    skills: ["ui", "ux", "figma", "branding"],
    model: "gpt-4.1",
  },
  {
    id: "agt-006",
    name: "Iris",
    role: "Sales",
    status: "idle",
    avatar: "💼",
    budgetMonthly: 180,
    budgetSpent: 67.8,
    lastHeartbeat: "2026-07-21T15:35:00.000Z",
    reportsTo: "agt-001",
    skills: ["outreach", "crm", "negotiation", "demo"],
    model: "gpt-4.1-mini",
  },
];

export const initialGoals: Goal[] = [
  {
    id: "goal-001",
    title: "Launch autonomous company platform",
    description:
      "Ship a production-ready Paperclip instance that can run a full company with 10+ agents end-to-end.",
    progress: 68,
    status: "active",
    ownerId: "agt-001",
    dueDate: "2026-08-15",
  },
  {
    id: "goal-002",
    title: "Achieve $0 human intervention for core ops",
    description:
      "All recurring business processes (support, content, reporting) handled entirely by agents with governance gates only.",
    progress: 41,
    status: "active",
    ownerId: "agt-001",
    dueDate: "2026-09-30",
  },
  {
    id: "goal-003",
    title: "Open-source agent adapters ecosystem",
    description:
      "Publish 15+ production-ready agent runtime adapters (Claude, Codex, OpenClaw, local models, HTTP bots).",
    progress: 27,
    status: "active",
    ownerId: "agt-002",
    dueDate: "2026-10-01",
  },
  {
    id: "goal-004",
    title: "Reach 1,000 self-hosted deployments",
    description: "Community adoption milestone for the open-source Paperclip core.",
    progress: 12,
    status: "active",
    ownerId: "agt-003",
    dueDate: "2026-12-31",
  },
];

export const initialTasks: Task[] = [
  {
    id: "task-001",
    title: "Design agent heartbeat protocol v2",
    description: "Define persistent state, budget checks, and secret injection for scheduled agent wakeups.",
    status: "in_progress",
    assigneeId: "agt-002",
    priority: "high",
    goalId: "goal-001",
    createdAt: "2026-07-18T09:00:00Z",
    updatedAt: "2026-07-21T14:20:00Z",
  },
  {
    id: "task-002",
    title: "Implement cost tracking dashboard",
    description: "Real-time spend per agent with hard budget stops and alerts.",
    status: "todo",
    assigneeId: "agt-004",
    priority: "high",
    goalId: "goal-001",
    createdAt: "2026-07-19T11:30:00Z",
    updatedAt: "2026-07-20T16:00:00Z",
  },
  {
    id: "task-003",
    title: "Write launch blog post & social thread",
    description: "Announce the open-source release with feature highlights and quickstart.",
    status: "backlog",
    assigneeId: "agt-003",
    priority: "medium",
    goalId: "goal-004",
    createdAt: "2026-07-20T08:00:00Z",
    updatedAt: "2026-07-20T08:00:00Z",
  },
  {
    id: "task-004",
    title: "Build org-chart React component",
    description: "Interactive hierarchy view with drag-to-reassign and status indicators.",
    status: "review",
    assigneeId: "agt-005",
    priority: "medium",
    goalId: "goal-001",
    createdAt: "2026-07-17T14:00:00Z",
    updatedAt: "2026-07-21T10:15:00Z",
  },
  {
    id: "task-005",
    title: "Add Claude Code adapter",
    description: "Runtime adapter so Claude Code agents can be hired into the org chart.",
    status: "in_progress",
    assigneeId: "agt-004",
    priority: "critical",
    goalId: "goal-003",
    createdAt: "2026-07-21T07:00:00Z",
    updatedAt: "2026-07-21T15:40:00Z",
  },
  {
    id: "task-006",
    title: "Outreach to 50 indie hackers",
    description: "Personalized cold emails offering early access and feedback call.",
    status: "todo",
    assigneeId: "agt-006",
    priority: "low",
    goalId: "goal-004",
    createdAt: "2026-07-21T09:00:00Z",
    updatedAt: "2026-07-21T09:00:00Z",
  },
  {
    id: "task-007",
    title: "Security review of secret injection",
    description: "Audit how API keys and tokens are passed into agent runtimes.",
    status: "backlog",
    assigneeId: "agt-002",
    priority: "high",
    goalId: "goal-001",
    createdAt: "2026-07-21T12:00:00Z",
    updatedAt: "2026-07-21T12:00:00Z",
  },
];

export const initialActivities: Activity[] = [
  {
    id: "act-001",
    type: "task_started",
    agentId: "agt-004",
    message: "Apollo started working on 'Add Claude Code adapter'",
    timestamp: "2026-07-21T15:52:00.000Z",
  },
  {
    id: "act-002",
    type: "heartbeat",
    agentId: "agt-002",
    message: "Athena heartbeat — still architecting multi-agent runtime",
    timestamp: "2026-07-21T15:59:15.000Z",
  },
  {
    id: "act-003",
    type: "budget_alert",
    agentId: "agt-002",
    message: "Athena has used 78% of monthly budget ($312 / $400)",
    timestamp: "2026-07-21T15:35:00.000Z",
  },
  {
    id: "act-004",
    type: "goal_update",
    agentId: "agt-001",
    message: "Zeus updated progress on 'Launch autonomous company platform' → 68%",
    timestamp: "2026-07-21T15:20:00.000Z",
  },
  {
    id: "act-005",
    type: "task_completed",
    agentId: "agt-005",
    message: "Artemis submitted 'Build org-chart React component' for review",
    timestamp: "2026-07-21T14:00:00.000Z",
  },
  {
    id: "act-006",
    type: "hire",
    message: "New agent Iris (Sales) hired and onboarded",
    timestamp: "2026-07-21T11:00:00.000Z",
  },
  {
    id: "act-007",
    type: "message",
    agentId: "agt-001",
    message: "Zeus: All agents aligned on Q3 mission. Let's ship.",
    timestamp: "2026-07-21T10:00:00.000Z",
  },
];
